### ISSUE TITLE
Nest comments cause usage guides generation failure

### ISSUE THREAD

**Issue by palmersp** [Taborlin/Taborlin#13]
Docs are not generated if there is a Taborlin comment nested within a selector css definition:

``` css
.selector {
   /* taborlin
       name: ...
       ...
  */
}
```

Can fail when using css pre-processors that allow module code within other modules:

``` scss
// Sass/Scss
   .selector {
      @import "other-module";
   }
```

https://github.com/topcoat/topdoc/issues/24
